/**
 * The single migration mechanism for the whole store (ADR-0017 §4, §8): a
 * Kysely `Migrator` over committed, dialect-specific `.sql` files. The auth
 * migrations are generated by Better Auth (`compileAuthMigrationSql`) and
 * committed; this runner applies them verbatim — the committed SQL is the
 * source of truth, never re-derived at apply time. Chunk 2's graph migrations
 * will drop into the same per-backend folders and run through this same runner.
 *
 * Migrations are applied explicitly via `db:migrate`, never on boot (ADR-0008).
 */
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { type Kysely, sql } from 'kysely';
import {
  type Migration,
  type MigrationProvider,
  type MigrationResult,
  Migrator,
} from 'kysely/migration';
import type { DatabaseBackend } from './config.js';

/**
 * Splits a `.sql` file into individual statements. The committed SQL is
 * machine-generated (Better Auth) or simple hand-written DDL — no semicolons
 * appear inside string literals or identifiers — so a split on `;` is exact.
 */
export function splitSqlStatements(sqlText: string): string[] {
  return sqlText
    .split(';')
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0);
}

/** A Kysely `MigrationProvider` that loads committed `.sql` files from a directory. */
export class SqlFileMigrationProvider implements MigrationProvider {
  constructor(private readonly directory: string) {}

  async getMigrations(): Promise<Record<string, Migration>> {
    const files = (await readdir(this.directory)).filter((file) => file.endsWith('.sql')).sort();
    const migrations: Record<string, Migration> = {};
    for (const file of files) {
      const name = file.replace(/\.sql$/, '');
      const filePath = path.join(this.directory, file);
      migrations[name] = {
        async up(db: Kysely<unknown>): Promise<void> {
          const text = await readFile(filePath, 'utf8');
          for (const statement of splitSqlStatements(text)) {
            await sql.raw(statement).execute(db);
          }
        },
      };
    }
    return migrations;
  }
}

export interface MigrateOptions {
  readonly db: Kysely<unknown>;
  readonly backend: DatabaseBackend;
  /** Migrations root; the runner reads `<rootDir>/<backend>`. */
  readonly rootDir: string;
}

/**
 * Applies all pending migrations for the backend, in filename order. Throws on
 * the first failure with the offending migration surfaced — never swallows.
 */
export async function migrateToLatest(
  options: MigrateOptions,
): Promise<readonly MigrationResult[]> {
  const directory = path.join(options.rootDir, options.backend);
  const migrator = new Migrator({
    db: options.db as Kysely<unknown>,
    provider: new SqlFileMigrationProvider(directory),
  });

  const { error, results } = await migrator.migrateToLatest();
  if (error !== undefined) {
    const failed = results?.find((result) => result.status === 'Error');
    const detail = failed !== undefined ? ` (failed at "${failed.migrationName}")` : '';
    throw new Error(
      `Database migration failed${detail}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  return results ?? [];
}
