/**
 * The single migration mechanism for the whole store (ADR-0017 §4, §8): a
 * Kysely `Migrator` over committed, dialect-specific `.sql` files. The auth
 * migrations are generated by Better Auth (`compileAuthMigrationSql`) and
 * committed; this runner applies them verbatim — the committed SQL is the
 * source of truth, never re-derived at apply time. The graph and subsequent
 * migrations live in the same per-backend folders and run through this same runner.
 *
 * Migrations are applied explicitly via `db:migrate`, never on boot (ADR-0008).
 */
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { type Kysely, sql } from 'kysely';
import {
  type Migration,
  type MigrationProvider,
  type MigrationResult,
  Migrator,
} from 'kysely/migration';
import type { DatabaseBackend } from './config.js';

/**
 * Strip `--` line comments (everything from `--` to the end of the line) so a
 * semicolon inside a comment can never sever a statement. The committed SQL is
 * machine-generated or simple hand-written DDL with no string literal or
 * identifier containing `--`, so a per-line cut at the first `--` is exact.
 */
function stripLineComments(sqlText: string): string {
  return sqlText
    .split('\n')
    .map((line) => {
      const comment = line.indexOf('--');
      return comment === -1 ? line : line.slice(0, comment);
    })
    .join('\n');
}

/**
 * Splits a `.sql` file into individual statements. `--` line comments are
 * stripped first (so a `;` written inside a comment does not split a statement),
 * then the comment-free SQL is split on `;`. The committed SQL is machine-
 * generated (Better Auth) or simple hand-written DDL — no semicolons appear
 * inside string literals or identifiers — so the split on `;` is exact.
 */
export function splitSqlStatements(sqlText: string): string[] {
  return stripLineComments(sqlText)
    .split(';')
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0);
}

/** A Kysely `MigrationProvider` that loads committed `.sql` files from a directory. */
export class SqlFileMigrationProvider implements MigrationProvider {
  constructor(private readonly directory: string) {}

  async getMigrations(): Promise<Record<string, Migration>> {
    const files = (await readdir(this.directory)).filter((file) => file.endsWith('.sql')).sort();
    const migrations: Record<string, Migration> = {};
    for (const file of files) {
      const name = file.replace(/\.sql$/, '');
      const filePath = path.join(this.directory, file);
      migrations[name] = {
        async up(db: Kysely<unknown>): Promise<void> {
          const text = await readFile(filePath, 'utf8');
          for (const statement of splitSqlStatements(text)) {
            await sql.raw(statement).execute(db);
          }
        },
      };
    }
    return migrations;
  }
}

export interface MigrateOptions<DB = unknown> {
  // Migrations are schema-agnostic (raw SQL), so any typed Kysely instance is
  // accepted — `Kysely` is invariant in its schema parameter, so this generic
  // avoids forcing callers to widen their typed instance.
  readonly db: Kysely<DB>;
  readonly backend: DatabaseBackend;
  /** Migrations root; the runner reads `<rootDir>/<backend>`. */
  readonly rootDir: string;
}

/** Build the backend's migrator over its committed `.sql` directory. */
function buildMigrator<DB>(options: MigrateOptions<DB>): Migrator {
  const directory = path.join(options.rootDir, options.backend);
  return new Migrator({ db: options.db, provider: new SqlFileMigrationProvider(directory) });
}

/** Surface a migration failure with the offending migration named — never swallow. */
function assertNoMigrationError(
  error: unknown,
  results: readonly MigrationResult[] | undefined,
): void {
  if (error === undefined) {
    return;
  }
  const failed = results?.find((result) => result.status === 'Error');
  const detail = failed !== undefined ? ` (failed at "${failed.migrationName}")` : '';
  throw new Error(
    `Database migration failed${detail}: ${error instanceof Error ? error.message : String(error)}`,
  );
}

/**
 * Applies all pending migrations for the backend, in filename order. Throws on
 * the first failure with the offending migration surfaced — never swallows.
 */
export async function migrateToLatest<DB = unknown>(
  options: MigrateOptions<DB>,
): Promise<readonly MigrationResult[]> {
  const { error, results } = await buildMigrator(options).migrateToLatest();
  assertNoMigrationError(error, results);
  return results ?? [];
}

/**
 * Applies migrations up to and including `targetMigration` (Kysely's `migrateTo`),
 * in filename order. Used to stage a backfill test: migrate to the migration
 * BEFORE the one under test, seed legacy data, then migrate the rest. Same
 * never-swallow error contract as {@link migrateToLatest}.
 */
export async function migrateTo<DB = unknown>(
  options: MigrateOptions<DB>,
  targetMigration: string,
): Promise<readonly MigrationResult[]> {
  const { error, results } = await buildMigrator(options).migrateTo(targetMigration);
  assertNoMigrationError(error, results);
  return results ?? [];
}
